import { parseColor } from "./contrast";
import type { ThemeScheme } from "./theme-tokens";
import { widgetThemeTokens, widgetTokens } from "./widget-tokens";

/** Android uses #AARRGGBB, unlike the design-tool export's #RRGGBBAA. */
export function toAndroidColor(value: string): string {
  const { alpha, rgb } = parseColor(value);
  const pair = (channel: number) =>
    Math.round(channel).toString(16).padStart(2, "0");
  const color = rgb.map(pair).join("");
  return `#${alpha < 1 ? pair(alpha * 255) : ""}${color}`;
}

function resourceName(role: string): string {
  return `musubi_widget_${role.replace(/[A-Z]/g, letter => `_${letter.toLowerCase()}`)}`;
}

/**
 * The default resource set includes geometry and scalable type. Night resources
 * override colours only, keeping dimensions identical between themes.
 */
export function renderAndroidWidgetTokensXml(scheme: ThemeScheme): string {
  const colors = Object.entries(widgetThemeTokens[scheme]).map(([role, value]) =>
    `  <color name="${resourceName(role)}">${toAndroidColor(value)}</color>`,
  );
  const dimensions = scheme === "light" ? [
    ...Object.entries(widgetTokens.layout).map(([role, value]) =>
      `  <dimen name="${resourceName(role)}">${value}dp</dimen>`,
    ),
    ...Object.entries(widgetTokens.type).map(([role, value]) =>
      `  <dimen name="${resourceName(role)}">${value}sp</dimen>`,
    ),
  ] : [];
  return [
    '<?xml version="1.0" encoding="utf-8"?>',
    "<!-- Generated by the design-system generate script.",
    "     Edit packages/design-system/src/widget-tokens.ts; do not edit this file. -->",
    "<resources>",
    ...colors,
    ...(dimensions.length > 0 ? ["", ...dimensions] : []),
    "</resources>",
    "",
  ].join("\n");
}
