import {
  fineSpacing,
  layoutSpacing,
  motionDurations,
  radii,
  spacing,
  typeSizes,
  type MotionRole,
  type RadiusName,
} from "./foundation-tokens";

const GENERATED_FILE_HEADER =
  "/* This file is generated by pnpm --filter @musubi/design-system generate. */";

/**
 * Tailwind colour names mapped onto the runtime theme variables in
 * `colors.css`. They reference variables rather than values, so one utility
 * serves both schemes and `data-theme` switches them without a variant.
 *
 * The first group keeps the names shadcn/ui components are written against, so
 * a component added through the shadcn CLI renders in Musubi's palette without
 * edits. The second names what Musubi has and shadcn does not.
 */
const colorRoles = {
  // shadcn/ui semantic roles.
  background: "var(--surface-canvas)",
  foreground: "var(--text-primary)",
  card: "var(--surface-panel)",
  "card-foreground": "var(--text-primary)",
  popover: "var(--surface-panel)",
  "popover-foreground": "var(--text-primary)",
  primary: "var(--control-fill)",
  "primary-foreground": "var(--control-on-fill)",
  secondary: "var(--surface-raised)",
  "secondary-foreground": "var(--text-primary)",
  muted: "var(--surface-raised)",
  "muted-foreground": "var(--text-muted)",
  accent: "var(--surface-raised)",
  "accent-foreground": "var(--text-primary)",
  destructive: "var(--accent-primary)",
  "destructive-foreground": "var(--accent-on-primary)",
  border: "var(--border-medium)",
  input: "var(--border-medium)",
  ring: "var(--accent-primary)",

  // Musubi surfaces, from the canvas up to the deepest well.
  canvas: "var(--surface-canvas)",
  panel: "var(--surface-panel)",
  raised: "var(--surface-raised)",
  sunken: "var(--surface-sunken)",
  overlay: "var(--surface-overlay)",
  // Ink tiers. `faint` never carries words; see theme-tokens.ts.
  "foreground-secondary": "var(--text-secondary)",
  faint: "var(--text-faint)",
  // Rules.
  "border-subtle": "var(--border-subtle)",
  "border-strong": "var(--border-strong)",
  // Shu vermilion: the one accent. Emphasis, destructive, focus.
  shu: "var(--accent-primary)",
  "shu-foreground": "var(--accent-on-primary)",
  // Check verdicts. Colour never carries a verdict alone.
  success: "var(--status-pass)",
  "success-fill": "var(--status-pass-fill)",
  warning: "var(--status-warn)",
  "warning-fill": "var(--status-warn-fill)",
  // The one colour a caller may set at runtime: a calendar's pigment,
  // passed as `--pigment` on the owning element.
  pigment: "var(--pigment, var(--text-muted))",
  // Ink that stays readable on the pigment: the owner sets `--pigment-ink`
  // from the calendar colour (getReadableEventTextColor) next to `--pigment`.
  "pigment-ink": "var(--pigment-ink, var(--text-primary))",
  // Allows `bg-transparent`, `text-current` and friends.
  transparent: "transparent",
  current: "currentColor",
  inherit: "inherit",
} as const;

/** Heights and widths that change between pointer and touch layouts. */
const responsiveSizes = {
  control: "var(--control-height)",
  "control-compact": "var(--compact-control-height)",
  row: "var(--row-min-height)",
  sidebar: "var(--sidebar-width)",
  inspector: "var(--inspector-width)",
  popover: "var(--popover-width)",
  // The one height every standing dialog holds, so switching between them
  // never resizes the window. The viewport still wins on a short screen.
  dialog: "min(47.5rem, 100dvh - 2 * var(--layer-viewport-gutter))",
  // Home-indicator inset, through the indirection stories can override.
  "safe-bottom": "var(--layer-safe-bottom)",
} as const;

/**
 * Musubi's responsive boundaries (see docs/ui/calendar-ui.md). Tailwind is
 * mobile first, so `sm:` is 600 px and up, `md:` 1024 and `lg:` 1440.
 */
const breakpoints = {
  sm: 600,
  md: 1024,
  lg: 1440,
} as const;

/** Dialog widths: one per role, never per screen. */
const containers = {
  compact: 440,
  form: 560,
  default: 720,
  wide: 960,
} as const;

const shadows = {
  overlay: "var(--shadow-overlay)",
} as const;

const fonts = {
  sans: "var(--font-sans)",
  serif: "var(--font-serif)",
  kanji: "var(--font-kanji)",
  mono: "var(--font-mono)",
} as const;

const layers = {
  "dialog-overlay": "var(--layer-dialog-overlay-z)",
  dialog: "var(--layer-dialog-z)",
  popover: "var(--layer-popover-z)",
  "dialog-overlay-elevated": "var(--layer-dialog-overlay-elevated-z)",
  "dialog-elevated": "var(--layer-dialog-elevated-z)",
  "popover-elevated": "var(--layer-popover-elevated-z)",
} as const;

function rem(size: number): string {
  return `${Number((size / 16).toFixed(4))}rem`;
}

function declarations(entries: Array<[string, string]>): string {
  return entries.map(([name, value]) => `  ${name}: ${value};`).join("\n");
}

function renderStaticTheme(): string {
  const entries: Array<[string, string]> = [
    // Only Musubi's values exist. Tailwind's palette, type ramp, radii,
    // shadows and spacing multiplier are cleared, so `bg-pink-500`, `text-xl`
    // or `p-13` are unknown classes rather than quiet drift.
    ["--color-*", "initial"],
    ["--spacing", "initial"],
    ["--spacing-*", "initial"],
    ["--text-*", "initial"],
    ["--radius-*", "initial"],
    ["--shadow-*", "initial"],
    ["--inset-shadow-*", "initial"],
    ["--drop-shadow-*", "initial"],
    ["--blur-*", "initial"],
    ["--font-*", "initial"],
    ["--breakpoint-*", "initial"],
    ["--container-*", "initial"],
    ["--animate-*", "initial"],
    ["--spacing-0", "0px"],
    ["--spacing-px", "1px"],
    ...Object.entries(fineSpacing).map(
      ([step, value]): [string, string] => [
        `--spacing-${step.replace(".", "\\.")}`,
        `${value}px`,
      ],
    ),
    ...Object.entries(spacing).map(
      ([step, value]): [string, string] => [`--spacing-${step}`, `${value}px`],
    ),
    ...Object.entries(layoutSpacing).map(
      ([step, value]): [string, string] => [`--spacing-${step}`, `${value}px`],
    ),
    ...Object.entries(typeSizes).map(
      ([size, value]): [string, string] => [`--text-${size}`, rem(value)],
    ),
    ...(Object.keys(radii) as RadiusName[])
      .filter((name) => name !== "pill")
      .map((name): [string, string] => [`--radius-${name}`, `${radii[name]}px`]),
    ...Object.entries(breakpoints).map(
      ([name, value]): [string, string] => [`--breakpoint-${name}`, rem(value)],
    ),
    ...Object.entries(containers).map(
      ([name, value]): [string, string] => [`--container-${name}`, rem(value)],
    ),
    ["--font-weight-*", "initial"],
    ["--font-weight-normal", "400"],
    ["--font-weight-medium", "500"],
    ["--tracking-*", "initial"],
    ["--tracking-normal", "0"],
    ["--tracking-label", "0.12em"],
    ["--tracking-wide", "0.2em"],
    ["--leading-*", "initial"],
    ["--leading-none", "1"],
    ["--leading-tight", "1.15"],
    ["--leading-snug", "1.3"],
    ["--leading-normal", "1.45"],
    ["--leading-relaxed", "1.6"],
    ...Object.entries(gridTemplates).map(
      ([name, value]): [string, string] => [`--grid-template-${name}`, value],
    ),
    ["--default-transition-duration", `${motionDurations.web.fast}ms`],
    ["--animate-spin", "spin 0.8s linear infinite"],
    ["--animate-pulse", "pulse 2s ease-in-out infinite"],
  ];

  return `@theme {\n${declarations(entries)}\n}`;
}

/**
 * Two sizes outside the type scale, both for orientation rather than reading:
 * the page title on the sign-in and onboarding card, and the faint kanji that
 * sits behind full-page states.
 */
const displaySizes = {
  display: "clamp(1.75rem, 6vw, 2.25rem)",
  ambient: "min(54vw, 42rem)",
} as const;

/**
 * Grid templates by role. `header-body`: a row sized to its content and a row
 * that takes the rest of the height, so the body's columns scroll on their own.
 */
const gridTemplates = {
  "rows-header-body": "auto minmax(0, 1fr)",
} as const;

function renderInlineTheme(): string {
  const entries: Array<[string, string]> = [
    ...Object.entries(displaySizes).map(
      ([name, value]): [string, string] => [`--text-${name}`, value],
    ),
    ...Object.entries(colorRoles).map(
      ([name, value]): [string, string] => [`--color-${name}`, value],
    ),
    ...Object.entries(responsiveSizes).map(
      ([name, value]): [string, string] => [`--spacing-${name}`, value],
    ),
    ...Object.entries(shadows).map(
      ([name, value]): [string, string] => [`--shadow-${name}`, value],
    ),
    ...Object.entries(fonts).map(
      ([name, value]): [string, string] => [`--font-${name}`, value],
    ),
  ];

  // `inline` makes utilities read the runtime variable itself, so the dark
  // scheme and the touch control heights apply without a variant.
  return `@theme inline {\n${declarations(entries)}\n}`;
}

/**
 * What an event block has room for, asked of the block itself rather than of
 * its duration: the block is a size container named `event-block`
 * (`@container-size/event-block`), and these reveal its rows as it grows. The
 * title is always there; the time comes next, then a second title line, then
 * the location. One scale for every density and zoom, because it reads the box.
 */
const eventBlockVariants = {
  "block-time": 30,
  "block-wrap": 44,
  "block-meta": 58,
} as const;

function renderVariants(): string {
  return Object.entries(eventBlockVariants)
    .map(
      ([name, height]) =>
        `@custom-variant ${name} (@container event-block (min-height: ${height}px));`,
    )
    .join("\n");
}

function renderUtilities(): string {
  const motion = (Object.keys(motionDurations.web) as MotionRole[]).map(
    (role) =>
      // Only the duration variable: Tailwind's transition-* utilities and the
      // enter/exit animations read it. Setting transition-duration itself would
      // animate every property, because transition-property defaults to all.
      `@utility duration-${role} {\n  --tw-duration: var(--motion-${role});\n}`,
  );
  const zLayers = Object.entries(layers).map(
    ([name, value]) => `@utility z-${name} {\n  z-index: ${value};\n}`,
  );

  // Rows and options sit inside scrolling or clipping surfaces, so their
  // keyboard ring is drawn inward instead of being cut off at the edge.
  const focus = "@utility focus-inset {\n  outline-offset: -2px;\n}";

  return [...motion, ...zLayers, focus].join("\n\n");
}

/**
 * The Tailwind v4 theme for web clients. Import it after `tailwindcss`:
 *
 *   @import "tailwindcss";
 *   @import "@musubi/design-system/tailwind.css";
 */
export function renderTailwindThemeCss(): string {
  return [
    GENERATED_FILE_HEADER,
    '@custom-variant dark (&:where([data-theme="dark"], [data-theme="dark"] *));',
    renderVariants(),
    renderStaticTheme(),
    renderInlineTheme(),
    renderUtilities(),
    "",
  ].join("\n\n");
}
